### ISSUE TITLE
Tooltip Comes down on updation in recyclerview of other fragment

### ISSUE THREAD

**Issue by SahajRana** [ViHtarb/Tooltip#19]
Tooltip Comes down on updating in recycler-view of other fragment ("Notice" : as in my app) so,
how to stop that?
 I have manually added this library but I couldn't fix it. If you are busy just tell me how to solve it so that I can do it by my own. Thanks :)

![tip1](https://cloud.githubusercontent.com/assets/16938202/21718985/2259cd2c-d441-11e6-9002-f59fa04adf03.png)
![tip2](https://cloud.githubusercontent.com/assets/16938202/21718986/225edc4a-d441-11e6-80f7-92586561e67d.png)

**Comment by ViHtarb** [comment]
Hi. In this moment i don`t know how fix this bug. But now i`m trying to fix it.

**Comment by ViHtarb** [comment]
@SahajRana Fixed, i will publish this fix in 0.1.9.2-SNAPSHOT

**Comment by ViHtarb** [comment]
@SahajRana SNAPSHOT is published. Please check is this issue fixed.

**Comment by SahajRana** [comment]
Thanks! it got fixed, but still it sometimes gets same behavior when activity is refreshed.
