### ISSUE TITLE
Gravity.CENTER_HORIZONTAL

### ISSUE THREAD

**Issue by illiaNaumov** [ViHtarb/Tooltip#22]
Hi! Could you please include Gravity.CENTER_HORIZONTAL to Tooltip's gravities? Thank you!!

**Comment by ViHtarb** [comment]
@illiaNaumov Hi! How do you see this? I see as Tooltip above of anchor view

**Comment by illiaNaumov** [comment]
@ViHtarb I see this under anchor view. As for me tooltips above anchor view should containt just a bit of text, but tooltip under anchor view may contain plenty of text and sometimes needs to be centered.

**Comment by ViHtarb** [comment]
Ok, i undestund you need text gravity, not tooltip gravity?

**Comment by illiaNaumov** [comment]
@ViHtarb No, I need tooltip gravity. I want to center it relatively to screen (or root view) width

**Comment by illiaNaumov** [comment]
@ViHtarb I want it to be like this 
![image](https://cloud.githubusercontent.com/assets/6940238/21996010/cc32302c-dc30-11e6-8557-af2578a2b896.png)

**Comment by ViHtarb** [comment]
@illiaNaumov ok, i will implement it

**Comment by ViHtarb** [comment]
@illiaNaumov i try to reproduce your sample but i always got normal result, may be you using the custom margin? 
![device-2017-01-17-201310](https://cloud.githubusercontent.com/assets/8938207/22033499/674f1f32-dcf1-11e6-8cc4-90e336f3faa2.png)

**Comment by illiaNaumov** [comment]
@ViHtarb You may try with Gravity.BOTTOM and in Tooltip class make small change: 
`case Gravity.BOTTOM:
                location.x = mContentView.getWidth() / 4f;
                location.y = anchorRect.bottom + mMargin;
                break;`

**Comment by ViHtarb** [comment]
@illiaNaumov yes, but on your screen Tooltip position is not normal and i want fix it

**Comment by illiaNaumov** [comment]
@ViHtarb Don't worry, your library works fine for me, Tooltip position is not normal because I've just played with your libriary.

**Comment by ViHtarb** [comment]
@illiaNaumov I thought it was a bug library :) But why need Gravity.CENTER_HORIZONTAL? Tootip always centered of anchored view if can.

**Comment by illiaNaumov** [comment]
@ViHtarb I just need it centered(by warframes) But I can imagine that it could be bug on large screens...

**Comment by ViHtarb** [comment]
@illiaNaumov You want same result? 
![image](https://cloud.githubusercontent.com/assets/8938207/22036704/139bd720-dcfd-11e6-97a8-1f17bb7a4fbe.png)

Or you want centering Tooltip of screen wigth?

**Comment by illiaNaumov** [comment]
@ViHtarb No, I want it like this
![tooltip example](https://cloud.githubusercontent.com/assets/6940238/22037111/a2b4821c-dcfe-11e6-8c29-d3febeb7893f.png)

**Comment by ViHtarb** [comment]
@illiaNaumov ok, you want centered Tooltip for screen width
Now you can get it so: Show Tooltip anchored on views container
Ex:

```xml
<LinearLayout
    android:id="@+id/container"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:layout_weight="1"/>
    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:layout_weight="1"/>
    <Button
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:text="Hello World!"
        android:layout_weight="1"/>
</LinearLayout>
```
```java
View view = findViewById(R.id.container);
Tooltip.Builder builderContainer = new Tooltip.Builder(view, R.style.Tooltip2)
        .setCancelable(true)
        .setDismissOnClick(false)
        .setCornerRadius(20f)
        .setText("TESTTTTTTTTTTTTTTTTT");
builderContainer.show();
```

**Comment by illiaNaumov** [comment]
@ViHtarb In my case I want third button to be anchor view (like on below screenshot)
![tooltip example 2](https://cloud.githubusercontent.com/assets/6940238/22038396/add6b728-dd03-11e6-8d67-216d844aa3b3.png)

**Comment by illiaNaumov** [comment]
@ViHtarb Is it possible?

**Comment by ViHtarb** [comment]
@illiaNaumov sorry but this not possible, i think it`s not normal positioning for Tooltip, if you want this logic, you need implement this self
