### ISSUE TITLE
Tooltip Elevation is it possible?

### ISSUE THREAD

**Issue by herisulistiyanto** [ViHtarb/Tooltip#28]
Hi,

So i'm using this Tooltip in the RecyclerView item which is in the first index, and when i scroll up, this Tooltip were overlap with Toolbar. Is it possible to make this tooltip elevation below the toolbar?

Thanks

**Comment by ViHtarb** [comment]
Hi, try to use 0.1.9.4-SNAPSHOT. It seems like how I fixed it in 0.1.9.4 version

**Comment by ViHtarb** [comment]
If it helped you, please let me know
