### ISSUE TITLE
custom view inside tooltip

### ISSUE THREAD

**Issue by AlirezaGhanbarinia** [ViHtarb/Tooltip#29]
hi
is it possible to add custom view inside the tooltip ballon instead of text?

**Comment by ViHtarb** [comment]
Hi in current implementation it is impossible but in future i think to add this feature

**Comment by ViHtarb** [comment]
Hi i implemented simple customization for using custom tooltip content view. That feature are available in new snapshot version 1.0.0-alpha01-SNAPSHOT. That first generation of this logic and can have bugs. Today i want to publish alpha01 snapshot to snapshots repo

**Comment by ivnsch** [comment]
How to do it?
