### ISSUE TITLE
Crash on Release flavor (Obfuscating)

### ISSUE THREAD

**Issue by herisulistiyanto** [ViHtarb/Tooltip#30]
Hi,

is there any documentation on proguard / dexguard this lib?
since it always crash with error 

> Caused by: java.lang.ClassNotFoundException: Didn't find class "com.tooltip.Tooltip$Builder"

here's my _dexguard_ rule for keeping this lib : 

> -keep class com.tooltip.** { * ; }
> -keep public class com.tooltip.Tooltip$* { * ; }
> -keep class com.tooltip.Tooltip$* { * ; }
> -keep interface com.tooltip.** { * ; }

but still not worked . . . 
any suggestion?

**Comment by ViHtarb** [comment]
Hi, thanks for bug report i reproduced it and fixed with adding this in proguard:
`-keep class com.tooltip.TooltipActionView`
or
`-keep class com.tooltip.TooltipActionView { *; }`
or
`-keep class com.tooltip.TooltipActionView {
    public <init>(android.content.Context);
}`

and i will add this rule to Tooltip library proguard

**Comment by ViHtarb** [comment]
I hope this helps you  :) please let me know
