### ISSUE TITLE
Navigation view toggle icon and grid view tooltip

### ISSUE THREAD

**Issue by mkamals1989** [ViHtarb/Tooltip#39]
Hi,

I would like to know is it possible to show a tooltip for the hamburger icon which we use to toggle the navigation view and also how to do it for gridview item. I have been trying to do so but not found any way to get it done.

Thanks in Advance.

**Comment by ViHtarb** [comment]
Hi, sorry for long wait, yes it`s possible. Tooltip can be attached to any view.
For attach to hamburger icon you need to get view(i don`t know better way for get it)
    private View findBackButton(Toolbar toolbar) {
        for (int i = 0, count = toolbar.getChildCount(); i < count; i++) {
            final View child = toolbar.getChildAt(i);
            if (child instanceof ImageButton) {
                return child;
            }
        }
        return null;
    }

and use it as
Tooltip tooltip = new Tooltip.Builder(findBackButton(toolbar))
        .setText("Hello tooltip")
        .show();

In gridview item you can attach tooltip to parent layout/container of item
