### ISSUE TITLE
aligning drawable top left

### ISSUE THREAD

**Issue by ayooladedeji** [ViHtarb/Tooltip#40]
is this possible?

**Comment by ViHtarb** [comment]
Arrow? or what?

**Comment by ayooladedeji** [comment]
I've put a drawable in my tooltip and had it start left but ideally i need a method like setDrawableStartTop so its in the top corner.

As an aside the arrow ofcourse is what points to the view anchor of the tooltip right?

Thanks for the very speedy reply

**Comment by ViHtarb** [comment]
I understood, but unfortunately this is impossible
