### ISSUE TITLE
How to dynamically update the tooltip text ?

### ISSUE THREAD

**Issue by eliusmamun** [ViHtarb/Tooltip#42]

**Comment by ViHtarb** [comment]
For now it`s impossible. That really need? If you need Tooltip with another text - create new Tooltip :)

**Comment by ViHtarb** [comment]
You can use that

Tooltip tooltip = new Tooltip.Builder(myIcon)
.setText("tooltip"))
.setCancelable(true)
.setDismissOnClick(true)
.setBackgroundColor(getResources().getColor(R.color.lighter_gray))
.setTextColor(getResources().getColor(R.color.black))
.setPadding(getResources().getDimension(R.dimen.size_13))
.setTextSize(R.dimen.text_extra_small)
.setArrowWidth((20f)
.build();

tooltip.show();
tooltip.dismiss();

**Comment by eliusmamun** [comment]
I need both to update the text dynamically and dismiss the tooltip from the code.

**Comment by ViHtarb** [comment]
Sorry but that not is possible for now if you want, you can to fork repo and modify Tooltips as you need
