### ISSUE TITLE
OnClickListener in not working.

### ISSUE THREAD

**Issue by testingflexsin** [ViHtarb/Tooltip#50]
Hi Team,
 
I had implements vihtarb tooltip in my project. But OnClickListener is not working in same.
my code is-

  Tooltip.Builder builder = new Tooltip.Builder(viewHolderGiftCard.ivFavorite, R.style.Tooltip2)
                .setCancelable(true)
                .setDismissOnClick(true)
                .setCornerRadius(10f)
                .setGravity(Gravity.BOTTOM)
                .setPadding(20f)
                .setText(contextA.getResources().getString(R.string.about_wishlist));
        builder.show();

        builder.setOnClickListener(new OnClickListener() {
            @Override
            public void onClick(@NonNull Tooltip tooltip) {
                Toast.makeText(contextA,"CLOSE",Toast.LENGTH_SHORT).show();
            }
        });

**Comment by testingflexsin** [comment]
I Sloved issue with .setDismissOnClick(false)

**Comment by ViHtarb** [comment]
Sorry for so long silence. What the version of library you use?
