### ISSUE TITLE
can't build project with version 0.2.0

### ISSUE THREAD

**Issue by mariooooo** [ViHtarb/Tooltip#54]
Can't build project with version 0.2.0
`Program type already present: android.support.v4.view.NestedScrollingChildHelper
Message{kind=ERROR, text=Program type already present: android.support.v4.view.NestedScrollingChildHelper, sources=[Unknown source file], tool name=Optional.of(D8)}
`
if add 

> compile 'com.github.vihtarb:tooltip:0.2.0' { exclude module: "support-compat" }

get error
`Could not find method com.github.vihtarb:tooltip:0.2.0() for arguments [build_dcfhzorziyirfx8lbdgh46fd7$_run_closure2$_closure10@4f4c13d2] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
`
maybe i do something wrong? version 0.1.9 work fine without 

> { exclude module: "support-compat" }

**Comment by ViHtarb** [comment]
Show me your dependencies please.

**Comment by ViHtarb** [comment]
To use `{exclude module: "support-compat"}` you need to wrap `'com.github.vihtarb:tooltip:0.2.0'` in the `()`

**Comment by ViHtarb** [comment]
@mariooooo здесь помогло? Возможно альфа версии уже и не нужно это решение

**Comment by mariooooo** [comment]
да в альфе все ок
