### ISSUE TITLE
method isShowing()

### ISSUE THREAD

**Issue by mariooooo** [ViHtarb/Tooltip#55]
method isShowing() always false doesn't work in version 0.1.9

> tooltip = new Tooltip.Builder(registration_or)
                .setText(getResources().getString(R.string.account_registration_instruction))
                .setCancelable(true)
                .setDismissOnClick(true)
                .setTextColor(getResources().getColor(R.color.white))
                .setBackgroundColor(getResources().getColor(R.color.mainGreen))
                .setTypeface(fontBoldIt)
                .setTextSize(18f)
                .setCornerRadius(5f)
                .setPadding(50f)
                .show();
        if(tooltip.isShowing()){
            System.out.println("TOOLTIP IS SHOWING!!!!!");
        }

**Comment by mariooooo** [comment]
Method isShowing() work fine. The problem is different, I have a button that, when pressed, opens or closes tooltip, but when tooltip is shown and i press the button to close tooltip, first triggered `(isCancelable && event.getAction() == MotionEvent.ACTION_OUTSIDE)` event then triggered my button click event, then i call `isShowing()` and always get false. So my tooltip first closes and then opens again instantly. Any idea how to fix this?
```
public void tooltipBtnClicked() {
        if (tooltip.isShowing()) {
            tooltip.dismiss();
        } else {
            tooltip.show();
        }
    }
```

**Comment by ViHtarb** [comment]
Hi. You can use setCancelable(false). This will disable dismissing the tooltip on outside touch

**Comment by mariooooo** [comment]
but I need dismiss when outside, on tooltip and button click

**Comment by ViHtarb** [comment]
Давай на русском) ты можешь объяснить зачем нужна такая логика? Просто в том ключе, в котором я понимаю тебя - это противоречит идее тултипов

**Comment by mariooooo** [comment]
ну у меня два инпута, использовать надо только один, между ними я поставил иконку знака вопроса по нажатию должна выскакивать инструкция, закрываться и открываться снова если надо. я не могу понять почему outside click так работает регистрирует два клика подряд

**Comment by ViHtarb** [comment]
Кажись я тебя понял. Собери тестовый проект и посмотри там все норм пашет? Я вроде бы это фиксил уже после 0.2.0 версии потому советую юзать 1.0.0-alpha01, хоть она и в альфе, но вроде бы достаточно стабильна, я у себя в проектах юзаю без проблем

**Comment by mariooooo** [comment]
попробовал 1.0.0-alpha01, все равно не получилось, для наглядности записал видео https://youtu.be/I_EWR-SsOOM 
еще какие-то идеи будут?

**Comment by mariooooo** [comment]
```
popupWindow.setBackgroundDrawable(new StateListDrawable())
popupWindow.setOutsideTouchable(true);
popupWindow.setFocusable(true);
```
вообщем setFocusable пофиксил все

**Comment by ViHtarb** [comment]
Да, setFocusable это фиксит) Сорри, я почему-то думал, что запаблишил этот фикс, в локальных изменениях он у меня есть и уже давно и в семпл проекте - такой баги нет.
На счет изменения размеров - в будущем мб сделаю, посмотрим, сейчас для "Simple text Tooltip implementation" есть возможность задавать setMaxWidth.
Начиная с alpha01 присутствует поддержка "хоть какой-то" кастомизации тултипов, так что в целом - можешь сам реализовать почти все что нужно.

**Comment by ViHtarb** [comment]
За возможность скроллить - пока что хз, опять же, под тултипами подразумевается просто всплывающая подсказка в которой не должно быть много текста, как пример - можно рассматривать тултипы от самих гуглов.

**Comment by mariooooo** [comment]
я вот еще пробовал ставить `setMaxWidth(MATCH_PARENT)` и оно почему-то не работает и на **0.2.0** и на **1.0.0-alpha01** , а еще забыл сказать что если setCancelable(true) то и Focusable(true) и наоборот иначе setCancelable(false) работать не будет если setFocusable(true), еще бы я конечно padding Left, Right, Top, Bottom добавил

**Comment by ViHtarb** [comment]
за setFocusable в курсе за setMaxWidth - это не одно и тоже что setWidth и он не принимает WRAP_CONTENT и тд

**Comment by ViHtarb** [comment]
для паддингов - на то я и сделал кастомизацию что бы можно было делать че и как хотите, в будущем реализация простого тултипа будет не final и его тоже можно будет править, но то потом
