### ISSUE TITLE
Doesn't work in fragments!!

### ISSUE THREAD

**Issue by leonardogazio** [ViHtarb/Tooltip#56]
Hey there.. Can't use that library in a MenuItem inflated inside a fragment class. Below my code;

`    @Override
    public void onCreateOptionsMenu(Menu menu, MenuInflater inflater) {
        inflater.inflate(R.menu.menu_rastreamento, menu);

        MenuItem itemajuda     = menu.findItem(R.id.action_ajuda);
        View     itemajudaview = itemajuda.getActionView();

        Tooltip tooltip = new Tooltip.Builder(itemajudaview)
                .setText("Precisa de ajuda?")
                .show();

        super.onCreateOptionsMenu(menu, inflater);
    }`

Any kind of help will be appreciated.

**Comment by ViHtarb** [comment]
Hi. What the version of library you use?
