### ISSUE TITLE
fontFamily doesn't work

### ISSUE THREAD

**Issue by CloudNine13** [ViHtarb/Tooltip#58]
I want to use this library, but It seems like I can't set my fonts for the text. `<item name="android:fontFamily">@font/name_of_the_font_bold_italic</item>` just doesn't work. 
How can I change my font? Is it an issue to be resolved or am I doing something wrong?

**Comment by ViHtarb** [comment]
Hi. What the version of library you use?

**Comment by ViHtarb** [comment]
Fixed in #59 1.0.0-alpha05-SNAPSHOT
