### ISSUE TITLE
Gravity issue

### ISSUE THREAD

**Issue by algoworks-raghav** [ViHtarb/Tooltip#61]
My tooltip is at bottom of edit text and then it goes to top if i set gravity to top. is there any way that tooltip will start automatically from top by default

**Comment by ViHtarb** [comment]
Please provide additioanl information: library version, android version

**Comment by algoworks-raghav** [comment]
implementation 'com.github.vihtarb:tooltip:0.1.9'
android version is 9

**Comment by ViHtarb** [comment]
@algoworks-raghav please try to use latest snapshot version

**Comment by algoworks-raghav** [comment]
how to do that

**Comment by ViHtarb** [comment]
it`s described on main page of repo in readme
https://github.com/ViHtarb/Tooltip/blob/master/README.md

**Comment by emergingcoders13** [comment]
also not working on latest update
