### ISSUE TITLE
Androidx support?

### ISSUE THREAD

**Issue by EmilAlipiev** [ViHtarb/Tooltip#65]
Does this library support androidx? if i dont have support/v4 referenced, i am getting a crash because of my project uses androidx. Can you upgrade it to androidx please.

**Comment by EmilAlipiev** [comment]
OK i see that develop branch uses already Androidx. how stable it it? can we get this merged into master?

**Comment by ViHtarb** [comment]
Hi. Use latest snapshot version. It is stable. For now it is dont ready to merge into master

**Comment by EmilAlipiev** [comment]
I am trying to get aar file but there is a difference between master and develop seems to be. Did you split library into library and core? I need probably both of them right?

**Comment by ViHtarb** [comment]
Yes. Lib in develop is splitted and its described in readme https://github.com/ViHtarb/Tooltip#100-alpha01-snapshot

**Comment by EmilAlipiev** [comment]
one last question, in the core there is still support v4 reference. is it necessary?

**Comment by ViHtarb** [comment]
it`s dependency of another dependency
